### ISSUE TITLE
Very small joint states numbers

### ISSUE THREAD

**Issue by manuelgitgomes** [ros4hri/hri_fullbody#2]
Hello all!
First of all, thank you for developing this package, as it is very useful. I first hear of you from your presentation at ROSCON 2022.

Now, when I tried to use the package, I cannot get a correct estimation of a 2D/3D skeleton pose using an RGB-D camera.

One thing I noticed is that most values for the joint states, as they are really small (near zero):

```
position: [0.0, 0.0, 0.0, 0.0, 0.0, 8.909208311087425e-11, 0.0, 1.631412601457227e-10, 0.0, 1.128599690590957e-10, 0.0,

1.1872098531808344e-10, 0.0, 6.628555182943805e-11, -1.8735825248397015e-11, -1.6691366356208623e-10, 

-0.09999942649329777, -0.39999999999998326, 0.6999999999999998, -3.535952186191125e-18]
```

These values, however, move consistently when the real world joint moves. That is, in a repeating joint movement (rotation of left arm, as an example), the joint values associated follow the movement. These joint values continue to be very small (in the same order of magnitude as the ones presented before).

To tackle this, I have tried to multiply these values by a large constant, with no success. Do you have any suggestion on what might be wrong?

I have a bagfile being uploaded to help you test in my conditions, if you want to.

Thank you for your attention.

Kind regards,
Manuel

**Comment by LorenzoFerriniCodes** [comment]
Hi @manuelgitgomes! 

I'm happy to hear you're finding the package useful. 

Regarding the small joint values: which ikpy version have you installed? Unfortunately, I noticed a similar behaviour in ikpy 3.3 ([here](https://github.com/Phylliade/ikpy/issues/123) the issue I opened some months ago), while ikpy 3.2.2 was working fine.

**Comment by LorenzoFerriniCodes** [comment]
Hi @manuelgitgomes, any update on this?
