### ISSUE TITLE
help with multi-body

### ISSUE THREAD

**Issue by juandpenan** [ros4hri/hri_fullbody#3]
Hey guys, I would like to know if you have a recommendation on what package/library to use to perform the body detection to extract the bounding boxes.

Thanks!

**Comment by LorenzoFerriniCodes** [comment]
Hi @juandpenan!

[YOLOv8](https://github.com/ultralytics/ultralytics) is a good candidate. For an increased performance, you might think to retrain it over humans focused datasets (e.g., [CrowdHuman](https://www.crowdhuman.org/)).

**Comment by juandpenan** [comment]
Hi @LorenzoFerriniCodes  Thanks for the suggestion, I will take a look to those.
