### ISSUE TITLE
Skeleton Detection not working with Depth !

### ISSUE THREAD

**Issue by AmirpooyaSh** [ros4hri/hri_fullbody#5]
Hey there,

I was trying to use HRI Fullbody package to detect a human inside Gazebo Simulation. 
My sensor is Astra Camera (The same attached to Turtle Bot robot), so the gazebo plugin is the same.
When I'm feeding the corresponding topics to the full_body launch file, it can recognize the human model and define the skeleton. However, when I'm trying to visualize it through Rviz, it seems that the publishing topic is not measuring x,y,z of the detected skeleton properly. 

Here is my modified launch file:

<launch>

    <arg name="rgb_camera" default="/camera/Astra_Left/Astra_Left/rgb"/>
    <arg name="rgb_camera_topic" default="$(arg rgb_camera)/image_raw"/>
    <arg name="rgb_camera_info" default="$(arg rgb_camera)/camera_info"/>

    <arg name="use_depth" default="True"/>
    
    <arg name="depth_camera" default="/camera/Astra_Left/Astra_Left/depth"/>
    <arg name="depth_camera_topic" default="$(arg depth_camera)/image_raw"/>
    <arg name="depth_camera_info" default="$(arg depth_camera)/camera_info"/>

    
    <arg name="stickman_debug" default="True"/>

     
    <arg name="single_body" default="True"/>

    <node name="hri_fullbody" pkg="hri_fullbody" type="detect" output="screen">
        <param name="use_depth" value="$(arg use_depth)"/>
        <param name="stickman_debug" value="$(arg stickman_debug)"/>
        <param name="single_body" value="$(arg single_body)"/>

        <remap from="/image" to="$(arg rgb_camera_topic)"/>
        <remap from="/camera_info" to="$(arg rgb_camera_info)"/>
        <remap from="/depth_image" to="$(arg depth_camera_topic)"/>
        <remap from="/depth_info" to="$(arg depth_camera_info)"/>
    </node>

</launch>

Then, the Gazebo Simulation and Rviz visualization results are like below:

![Screenshot from 2023-09-05 21-59-34](https://github.com/ros4hri/hri_fullbody/assets/120086375/f9eee059-f934-4910-befd-af36ec604fa7)

![Screenshot from 2023-09-05 22-00-01](https://github.com/ros4hri/hri_fullbody/assets/120086375/0fb80c97-be45-4c22-afe5-bb7b172c9172)

I haven't tested it using real Astra Camera yet. I assume that the real RGB-D sensor would make it work and it's more or less an issue related to the astra camera's Gazebo plugin (I also tested it using Xtion Gazebo Plugin, got into the same issue).

Here is also my astra.xacro file:

<?xml version="1.0"?>
<robot name="sensor_astra" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />
  

  <xacro:property name="astra_dae_display_scale"   value="1" />

  
  <xacro:macro name="sensor_astra" params="parent name:=Astra *origin">
    <joint name="${name}_camera_rgb_joint" type="fixed">
      <xacro:insert_block name="origin" /> 
      <parent link="${parent}"/>
      <child link="${name}_camera_rgb_frame" />
    </joint>
    <link name="${name}_camera_rgb_frame"/>

    <joint name="${name}_camera_rgb_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${name}_camera_rgb_frame" />
      <child link="${name}_camera_rgb_optical_frame" />
    </joint>
    <link name="${name}_camera_rgb_optical_frame"/>

    <joint name="${name}_camera_joint" type="fixed">
      <origin xyz="0 0 0"
              rpy="0 0 0"/>
      <parent link="${name}_camera_rgb_frame"/>
      <child link="${name}_camera_link"/>
    </joint>
    <link name="${name}_camera_link">
      <visual>
        <origin xyz="-0.04 0.02 -0.01" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <mesh filename="file:///tiago_public_ws/src/tiago_patient_simulation/urdf/astra/meshes/astra.dae" scale="${astra_dae_display_scale} ${astra_dae_display_scale} ${astra_dae_display_scale}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <box size="0.0400 0.1650 0.0300"/>
      </geometry>
      </collision>
      <inertial>
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
                 iyy="0.000498940" iyz="0.0"
                 izz="0.003879257" />
      </inertial>
    </link>

    <joint name="${name}__camera_depth_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${name}_camera_rgb_frame" />
      <child link="${name}_camera_depth_frame" />
    </joint>
    <link name="${name}_camera_depth_frame"/>

    <joint name="${name}_camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${name}_camera_depth_frame" />
      <child link="${name}"/>
    </joint>
    <link name="${name}"/>

    

    <gazebo reference="${name}_camera_link">  
      <sensor type="depth" name="$astra">
        <always_on>true</always_on>
        <update_rate>20.0</update_rate>
        <camera>
            <horizontal_fov>${70.0*M_PI/180.0}</horizontal_fov>
          <image>
            <format>B8G8R8</format>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.4</near>
            <far>15.0</far>
          </clip>
        </camera>
        <plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
          <cameraName>camera/${name}</cameraName>
          <alwaysOn>true</alwaysOn>
          <updateRate>10</updateRate>
          <imageTopicName>${name}/rgb/image_raw</imageTopicName>
          <depthImageTopicName>${name}/depth/image_raw</depthImageTopicName>
          <pointCloudTopicName>${name}/depth/points</pointCloudTopicName>
          <cameraInfoTopicName>${name}/rgb/camera_info</cameraInfoTopicName>
          <depthImageCameraInfoTopicName>${name}/depth/camera_info</depthImageCameraInfoTopicName>
          <frameName>${name}</frameName>
          <baseline>0.1</baseline>
          <distortion_k1>0.0</distortion_k1>
          <distortion_k2>0.0</distortion_k2>
          <distortion_k3>0.0</distortion_k3>
          <distortion_t1>0.0</distortion_t1>
          <distortion_t2>0.0</distortion_t2>
          <pointCloudCutoff>0.4</pointCloudCutoff>
          <pointCloudCutoffMax>8.0</pointCloudCutoffMax>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>

I'd appreciate it if someone could help me with this problem.

**Comment by skadge** [comment]
hi!
First, really cool to see hri_fullbody used in simulation!! well done!

We use a patch of pixels from the depth map (ie, *not* the point cloud) to estimate the depth. According to https://ros.org/reps/rep-0118.html , depth can be encoded either as a 16bit/milimeters or 32bits/meters.

Our code has been develop with the RealSense camera, that uses 16bits/milimeters, and does *not* check for 32bits/float (I assume your camera publishes in that format) -> the distances are divided by 1000, which cause the wrong distance estimation.

The fix should be fairly easy to implement, around that line https://github.com/ros4hri/hri_fullbody/blob/master/src/hri_fullbody/fullbody_detector.py#L741 and that line https://github.com/ros4hri/hri_fullbody/blob/master/src/hri_fullbody/rs_to_depth.py#L35, checking somewhere for the depth image format.

Do you feel like submitting a PR? it would be much appreaciated!

Do you

**Comment by AmirpooyaSh** [comment]
Hey @skadge,

As far as I understand the function "rgb_to_xyz" is trying to do the conversion and by just removing the division of z to 1000 the localization will get fixed. 

The code below started to work on localizing a single skeleton correctly.

def rgb_to_xyz(
        x_rgb,
        y_rgb,
        rgb_camera_info,
        depth_camera_info,
        depth_data,
        roi_xmin = 0.,
        roi_ymin = 0.):
    depth_model = PinholeCameraModel()
    rgb_model = PinholeCameraModel()

    depth_model.fromCameraInfo(depth_camera_info)
    rgb_model.fromCameraInfo(rgb_camera_info)

    x_rgb = x_rgb + (roi_xmin * rgb_model.width)
    y_rgb = y_rgb + (roi_ymin * rgb_model.height)

    if x_rgb > rgb_model.width:
        x_rgb = rgb_model.width - 1
    if y_rgb > rgb_model.height:
        y_rgb = rgb_model.height - 1

    x_d = int(((x_rgb - rgb_model.cx())
               * depth_model.fx()
               / rgb_model.fx())
              + depth_model.cx())
    y_d = int(((y_rgb - rgb_model.cy())
               * depth_model.fy()
               / rgb_model.fy())
              + depth_model.cy())
    z = depth_data[y_d][x_d]
    x = (x_d - depth_model.cx())*z/depth_model.fx()
    y = (y_d - depth_model.cy())*z/depth_model.fy()

    return np.array([x, y, z])

![Screenshot from 2023-09-07 13-10-06](https://github.com/ros4hri/hri_fullbody/assets/120086375/2488eb6d-8e4f-4a37-bcee-28b0150398dc)
![Screenshot from 2023-09-07 13-11-05](https://github.com/ros4hri/hri_fullbody/assets/120086375/cb4d314c-703c-4ebd-9e2a-75d3876e2239)

Before asking a PR for that, I'd like to double-check with another problem I face now. For single skeleton detection, everything is fine, but when I'm trying to use multiple skeleton detection (In the simulation), I get the below error:

[INFO] [1694110389.553657, 0.000000]: Using depth camera for body position estimation: True
[INFO] [1694110389.554227, 0.000000]: Setting up for multibody pose estimation
[INFO] [1694110389.554737, 0.000000]: Waiting for ids on /humans/bodies/tracked
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 237, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/tiago_public_ws/src/hri_fullbody/nodes/detect", line 100, in do_diagnostics
    KeyValue(key="Last detected body ID", value=str(next(reversed(self.detected_bodies)))),
StopIteration

About a PR, yes why not ! However, I'm not that expert on working with GitHub, so not sure how can I do that :D !

**Comment by severin-lemaignan** [comment]
Regarding the change: the PR needs to handle both the 32bits encoding (ie, depth in meters) and the 16bits encoding (depth in mm).

For the other issue, please open a separate issue.

**Comment by severin-lemaignan** [comment]
Regarding how to create pull requests: have a look here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request !

**Comment by severin-lemaignan** [comment]
Closing the issue as it should be fixed by #6
